### ISSUE TITLE
Parametric 270 Removable Hinge v19 - Surfaces not prallel

### ISSUE THREAD

**Issue by 310weber** [LoganFraser/VoronMods#2]
Logan - thank you so much for this design.  The hinges are awesome.

One quick bit of feedback.  Some of the surfaces of the hinges are not perfectly parallel with each other in the model. For example, the front face and the face of the voron logo are 0.103 deg off from each other.
![image](https://user-images.githubusercontent.com/2540542/151719901-2e48ec28-cebc-49a1-828c-8f8d54151fdd.png)

This causes a cosmetic issue when printing the logo - one small corner of the logo starts printing on one layer, while the rest of the logo prints on the next.
![image](https://user-images.githubusercontent.com/2540542/151719949-fea7aa2f-66f2-40c4-99c2-e98db4956e42.png)

**Comment by 310weber** [comment]
I was able to fix the issue by deleting most of the "Position" features from the design history.
[Parametric 270 Removable Hinge v20.zip](https://github.com/LoganFraser/VoronMods/files/7975478/Parametric.270.Removable.Hinge.v20.zip)

**Comment by LoganFraser** [comment]
Thanks for noticing this, I went through and deleted the position features and it's clean now.
